enum ErrorCodes {
    RECORD_NOT_FOUND,
    TRANSACTION_FAILURE,
    CONFLICT,
    INVALID_REPOSITORY,
    NO_PROJECT_IDEA,
    CHANNEL_CREATION_ERROR,
    PARENT_PROJECT_PRIVATE,
    PROJECT_CREATION_ERROR,
    USER_NOT_EXIST
}

export default ErrorCodes
