import { Metadata } from 'next'
import ApplicantsSection from './applicants-section'

export const metadata: Metadata = {
    title: 'Applicants',
    description: 'Generated by create next app'
}

export default function ApplicantsPage() {
    return <ApplicantsSection />
}
