import '../globals.css'
import type { Metadata } from 'next'
import { LateralNav } from '../../components/navs/lateral-nav'
import { ScrollArea } from '@/components/ui/scroll-area'
import { getUser } from '@/backend/core/shared/get-user'

export const metadata: Metadata = {
    title: 'Member - CoderConnection',
    description: 'Generated by create next app'
}

export default async function RootLayout({
    children
}: {
    children: React.ReactNode
}) {
    return (
        <div className="flex h-screen w-screen">
            <LateralNav />
            <div className="h-screen flex-1 overflow-y-auto px-10 pt-8">
                {children}
            </div>
        </div>
    )
}
