import '../globals.css'
import type { Metadata } from 'next'
import { LateralNav } from '../../components/navs/lateral-nav'

export const metadata: Metadata = {
    title: 'Member - CoderConnection',
    description: 'Generated by create next app'
}

export default async function RootLayout({
    children
}: {
    children: React.ReactNode
}) {
    return (
        <div className="flex min-h-screen w-screen">
            <LateralNav className="sticky left-0 top-0 h-screen" />
            <div className="flex-1 overflow-y-auto px-10 py-8">{children}</div>
        </div>
    )
}
