import type { Metadata } from 'next'
import { Nav } from '../../components/navs/lateral-nav'
import { ScrollArea } from '@/components/ui/scroll-area'

export const metadata: Metadata = {
    title: 'Member - CoderConnection',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: {
    children: React.ReactNode
}) {
    return (
        <div className="flex h-screen">
            <Nav />
            <ScrollArea className="flex-1">
                <div className="px-10 pt-8">{children}</div>
            </ScrollArea>
        </div>
    )
}
