import '../globals.css'
import type { Metadata } from 'next'
import Nav from '@/components/navs/nav'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: {
    children: React.ReactNode
}) {
    return (
        <div className="min-h-screen">
            <Nav />
            <div>{children}</div>
        </div>
    )
}
